### ISSUE TITLE
No matching records found

### ISSUE THREAD

**Issue by dirsigler** [mziyabo/argocd-trivy-extension#4]
We installed the Plugin into a ArgoCD installation of version `v2.10.6+d504d2b`.

I can see in a given namespace and cluster my Application with a Replicaset and Pod. "Underneath" the Pod is then my VulnerabilityscanReport by Trivy-Operator.
If I click into the Pod of my Microservice I also see the tab "Vulnerabilities".

Unfortunately it does not list the found vulnerabilities and only responds with "No matching records found". If I look into the attached VulnerabilityReport of this Pod I can clearly see found issues, so it should show something.

By any chance you know if there are any prerequisits or a specific setup that is missing?

**Comment by mziyabo** [comment]
@dirsigler Please check the developer tools console in your browser, there should be an error message indicating the URL at which the extension tried to access the vulnerability report. 

If you tried to navigate to that URL it should return the report. Otherwise you can share the URL here and the name of the vulnerability report (mask out or remove any of the sensitive stuff). 

It does happen that there is a delay where we await report generation and the extension in that case can show missing data. Doesn't seem like the case here but worth mentioning.

**Comment by dirsigler** [comment]
Hey @mziyabo,

thank you for your swift efforts to help out.
It turned out my whole Trivy Operator setup was not working as expected, even tho creating VulnerabilityReports.

What exactly the culprit was is out of my current knowledge, but it works now flawless.

**Comment by alekslebedev** [comment]
@dirsigler Could you tell what was the root cause of the problem? ?
